name: "ZIP"

on:
  push:
    tags:
      - "v*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Release ZIP
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'portal.zip'
          exclusions: '*.git* README*'
