name: "ZIP"

on:
  push:
    tags:
      - "v*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: ZIP It
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'portal.zip'
          exclusions: '*.git* README*'

      - name: Release Files
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: *.zip
